[package]
name = "bissextile_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
glib = "0.10.0"
gio = "0.9.0"
#chrono = "0.4"
